version: 2.1

parameters:
  deploy-bgu-mc-cardservice:
    type: boolean
    default: true

jobs:
  bgu-mc-cardservice:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout

      # build image
      - run: |         
          docker info
          docker build -t aspnetapp -f BGU.MarvelChampions.CardService/Dockerfile .

      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker tag aspnetapp registry.heroku.com/$HEROKU_MC_CARDSERVICE/web
          docker push registry.heroku.com/$HEROKU_MC_CARDSERVICE/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a $HEROKU_MC_CARDSERVICE

workflows:
  deploy-bgu-mc-cardservice:
    when: << pipeline.parameters.deploy-bgu-mc-cardservice >>
    jobs:
      - bgu-mc-cardservice