version: 2.1

parameters:
  deploy-apigateway:
    type: boolean
    default: false
  deploy-cardservice:
    type: boolean
    default: false
  deploy-deckservice:
    type: boolean
    default: false
  deploy-packservice:
    type: boolean
    default: false
  deploy-webapp:
    type: boolean
    default: false

jobs:
  build-n-push:
    parameters:
      docker-file:
        type: string
      app-name:
        type: string
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout

      # build image
      - run: |
          docker info
          docker build -t aspnetapp -f << parameters.docker-file >> .

      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker tag aspnetapp registry.heroku.com/<< parameters.app-name >>/web
          docker push registry.heroku.com/<< parameters.app-name >>/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a << parameters.app-name >>    

workflows:
  deploy-bgu-mc-apigateway:
    when: << pipeline.parameters.deploy-apigateway >>
    jobs:
      - build-n-push:
          docker-file: 'BGU.MarvelChampions.ApiGateway/Dockerfile'
          app-name: '$HEROKU_MC_APIGATEWAY'
  deploy-bgu-mc-cardservice:
    when: << pipeline.parameters.deploy-cardservice >>
    jobs:
      - build-n-push:
          docker-file: 'BGU.MarvelChampions.CardService/Dockerfile'
          app-name: '$HEROKU_MC_CARDSERVICE'
  deploy-bgu-mc-deckservice:
    when: << pipeline.parameters.deploy-deckservice >>
    jobs:
      - build-n-push:
          docker-file: 'BGU.MarvelChampions.DeckService/Dockerfile'
          app-name: '$HEROKU_MC_DECKSERVICE'
  deploy-bgu-mc-packservice:
    when: << pipeline.parameters.deploy-packservice >>
    jobs:
      - build-n-push:
          docker-file: 'BGU.MarvelChampions.PackService/Dockerfile'
          app-name: '$HEROKU_MC_PACKSERVICE'
  deploy-bgu-webapp:
    when: << pipeline.parameters.deploy-webapp >>
    jobs:
      - build-n-push:
          docker-file: 'BoardGameUniverse.WebApp/Dockerfile'
          app-name: '$HEROKU_WEBAPP'